// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalApp.Infrastructure.Persistence;

#nullable disable

namespace RentalApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RentalAppDbContext))]
    partial class RentalAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RentalApp.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(191)
                        .HasColumnType("varchar(191)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "10000000-0000-0000-0000-000000000001",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@local.test",
                            PasswordHash = "AQAAAAIAAYagAAAAEAARIjNEVWZ3iJmqu8zd7v+9B/m68fN7pVomQZIk2QhdaT58yv9z9zo2k0tHeC3mUA==",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "admin.local"
                        },
                        new
                        {
                            UserId = "10000000-0000-0000-0000-000000000002",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer@local.test",
                            PasswordHash = "AQAAAAIAAYagAAAAEBAhMkNUZXaHmKm6y9zt/g/dvnXaKV7KW02eQ7Sj/tJyjyBsxoyog7jpqOJeHhupEg==",
                            Status = "Active",
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "customer.local"
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Booking", b =>
                {
                    b.Property<string>("BookingId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("booking_id");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<string>("CancellationPolicyId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("cancellation_policy_id");

                    b.Property<DateTime?>("CancelledAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("completed_at");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("confirmed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("EndAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_at");

                    b.Property<string>("HoldId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("hold_id");

                    b.Property<DateTime>("StartAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.HasIndex("CancellationPolicyId");

                    b.HasIndex("HoldId")
                        .IsUnique()
                        .HasDatabaseName("uq_bookings_hold");

                    b.HasIndex("Status", "BookingDate")
                        .HasDatabaseName("ix_bookings_status_date");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_bookings_user_created");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.BookingItem", b =>
                {
                    b.Property<string>("BookingItemId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("booking_item_id");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("booking_id");

                    b.Property<string>("BookingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("booking_mode");

                    b.Property<string>("BucketId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("bucket_id");

                    b.Property<string>("CourtId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("court_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("line_total");

                    b.Property<byte>("SlotQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("slot_qty");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("BookingItemId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_booking_items_booking");

                    b.HasIndex("BucketId");

                    b.HasIndex("CourtId", "BucketId")
                        .HasDatabaseName("ix_booking_items_court_bucket");

                    b.ToTable("booking_items", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.CancellationPolicy", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("policy_id");

                    b.Property<decimal>("CancelFeePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("cancel_fee_percent");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<int>("MinHoursBeforeStart")
                        .HasColumnType("int")
                        .HasColumnName("min_hours_before_start");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("policy_name");

                    b.Property<decimal?>("RefundPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("refund_percent");

                    b.Property<string>("RefundStrategy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("refund_strategy");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("PolicyId");

                    b.HasIndex("IsActive");

                    b.ToTable("cancellation_policies", (string)null);

                    b.HasData(
                        new
                        {
                            PolicyId = "30000000-0000-0000-0000-000000000001",
                            CancelFeePercent = 0m,
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MinHoursBeforeStart = 2,
                            PolicyName = "Standard 2 Hour Refund",
                            RefundPercent = 100m,
                            RefundStrategy = "Full",
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.CheckoutOrder", b =>
                {
                    b.Property<string>("OrderId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)")
                        .HasDefaultValue("VND")
                        .HasColumnName("currency");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("subtotal_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("OrderId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_checkout_orders_status_created");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_checkout_orders_user_created");

                    b.ToTable("checkout_orders", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.CheckoutOrderItem", b =>
                {
                    b.Property<string>("OrderItemId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("order_item_id");

                    b.Property<string>("BookingId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("order_id");

                    b.HasKey("OrderItemId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("ix_checkout_order_items_booking");

                    b.HasIndex("OrderId", "BookingId")
                        .IsUnique()
                        .HasDatabaseName("uq_checkout_order_booking");

                    b.ToTable("checkout_order_items", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Court", b =>
                {
                    b.Property<string>("CourtId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("court_id");

                    b.Property<string>("CourtCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("court_code");

                    b.Property<string>("CourtName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("court_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("MaintenanceReason")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("maintenance_reason");

                    b.Property<byte>("SortOrder")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("CourtId");

                    b.HasIndex("CourtCode")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("courts", (string)null);

                    b.HasData(
                        new
                        {
                            CourtId = "20000000-0000-0000-0000-000000000001",
                            CourtCode = "C01",
                            CourtName = "Court 01",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SortOrder = (byte)1,
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourtId = "20000000-0000-0000-0000-000000000002",
                            CourtCode = "C02",
                            CourtName = "Court 02",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SortOrder = (byte)2,
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourtId = "20000000-0000-0000-0000-000000000003",
                            CourtCode = "C03",
                            CourtName = "Court 03",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SortOrder = (byte)3,
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourtId = "20000000-0000-0000-0000-000000000004",
                            CourtCode = "C04",
                            CourtName = "Court 04",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SortOrder = (byte)4,
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourtId = "20000000-0000-0000-0000-000000000005",
                            CourtCode = "C05",
                            CourtName = "Court 05",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SortOrder = (byte)5,
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourtId = "20000000-0000-0000-0000-000000000006",
                            CourtCode = "C06",
                            CourtName = "Court 06",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SortOrder = (byte)6,
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourtId = "20000000-0000-0000-0000-000000000007",
                            CourtCode = "C07",
                            CourtName = "Court 07",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SortOrder = (byte)7,
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourtId = "20000000-0000-0000-0000-000000000008",
                            CourtCode = "C08",
                            CourtName = "Court 08",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SortOrder = (byte)8,
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            CourtId = "20000000-0000-0000-0000-000000000009",
                            CourtCode = "C09",
                            CourtName = "Court 09",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            SortOrder = (byte)9,
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.CourtBucket", b =>
                {
                    b.Property<string>("CourtId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("court_id");

                    b.Property<string>("BucketId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("bucket_id");

                    b.Property<uint>("LockVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("lock_version");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("None")
                        .HasColumnName("mode");

                    b.Property<string>("PrivateHoldId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("private_hold_id");

                    b.Property<byte>("SharedCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)8)
                        .HasColumnName("shared_capacity");

                    b.Property<byte>("SharedReserved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("shared_reserved");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("CourtId", "BucketId");

                    b.HasIndex("BucketId");

                    b.HasIndex("Mode");

                    b.ToTable("court_buckets", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Hold", b =>
                {
                    b.Property<string>("HoldId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("hold_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("HoldId");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_holds_status_expires");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_holds_user_created");

                    b.ToTable("holds", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.HoldItem", b =>
                {
                    b.Property<string>("HoldItemId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("hold_item_id");

                    b.Property<string>("BookingMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("booking_mode");

                    b.Property<string>("BucketId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("bucket_id");

                    b.Property<string>("CourtId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("court_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("HoldId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("hold_id");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("line_total");

                    b.Property<byte>("SlotQty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("slot_qty");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("HoldItemId");

                    b.HasIndex("BucketId");

                    b.HasIndex("CourtId", "BucketId")
                        .HasDatabaseName("ix_hold_items_court_bucket");

                    b.HasIndex("HoldId", "CourtId", "BucketId", "BookingMode")
                        .IsUnique()
                        .HasDatabaseName("uq_hold_items_scope");

                    b.ToTable("hold_items", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<string>("IdempotencyId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("idempotency_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("endpoint");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("IdempotencyKeyValue")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseSnapshot")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("response_snapshot");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("int")
                        .HasColumnName("response_status");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("scope");

                    b.HasKey("IdempotencyId");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_idempotency_expires");

                    b.HasIndex("Scope", "Endpoint", "IdempotencyKeyValue")
                        .IsUnique()
                        .HasDatabaseName("uq_idempotency_scope_endpoint_key");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("used_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("TokenId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.PricingRule", b =>
                {
                    b.Property<string>("PricingRuleId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("pricing_rule_id");

                    b.Property<string>("AppliesTo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("applies_to");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DayType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("day_type");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("effective_to");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<decimal>("PrivateRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("private_rate");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("rule_name");

                    b.Property<decimal>("SharedRate")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("shared_rate");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("WeekendMarkupPct")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weekend_markup_pct");

                    b.HasKey("PricingRuleId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("IsActive", "EffectiveFrom");

                    b.ToTable("pricing_rules", (string)null);

                    b.HasData(
                        new
                        {
                            PricingRuleId = "40000000-0000-0000-0000-000000000001",
                            AppliesTo = "Any",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "10000000-0000-0000-0000-000000000001",
                            DayType = "Weekday",
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new TimeOnly(22, 0, 0),
                            IsActive = true,
                            PrivateRate = 280000m,
                            RuleName = "Weekday Baseline",
                            SharedRate = 45000m,
                            StartTime = new TimeOnly(6, 0, 0),
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeekendMarkupPct = 0m
                        },
                        new
                        {
                            PricingRuleId = "40000000-0000-0000-0000-000000000002",
                            AppliesTo = "Any",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = "10000000-0000-0000-0000-000000000001",
                            DayType = "Weekend",
                            EffectiveFrom = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EndTime = new TimeOnly(22, 0, 0),
                            IsActive = true,
                            PrivateRate = 280000m,
                            RuleName = "Weekend Baseline",
                            SharedRate = 45000m,
                            StartTime = new TimeOnly(6, 0, 0),
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            WeekendMarkupPct = 20m
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Role", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = "00000000-0000-0000-0000-000000000001",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = "00000000-0000-0000-0000-000000000002",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.TimeBucket", b =>
                {
                    b.Property<string>("BucketId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("bucket_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<short>("DurationMin")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_min");

                    b.Property<DateTime>("EndAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_at");

                    b.Property<DateTime>("StartAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_at");

                    b.HasKey("BucketId");

                    b.HasIndex("StartAt");

                    b.HasIndex("StartAt", "EndAt")
                        .IsUnique();

                    b.ToTable("time_buckets", (string)null);
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UserProfile", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmergencyContact")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("emergency_contact");

                    b.Property<string>("FullName")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId");

                    b.ToTable("user_profiles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "10000000-0000-0000-0000-000000000001",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Admin Local",
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = "10000000-0000-0000-0000-000000000002",
                            CreatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Customer Local",
                            UpdatedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasPrecision(6)
                        .HasColumnType("datetime(6)")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "10000000-0000-0000-0000-000000000001",
                            RoleId = "00000000-0000-0000-0000-000000000001",
                            AssignedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            UserId = "10000000-0000-0000-0000-000000000002",
                            RoleId = "00000000-0000-0000-0000-000000000002",
                            AssignedAt = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Booking", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.CancellationPolicy", "CancellationPolicy")
                        .WithMany("Bookings")
                        .HasForeignKey("CancellationPolicyId");

                    b.HasOne("RentalApp.Domain.Entities.Hold", "Hold")
                        .WithOne()
                        .HasForeignKey("RentalApp.Domain.Entities.Booking", "HoldId");

                    b.HasOne("RentalApp.Domain.Entities.AppUser", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CancellationPolicy");

                    b.Navigation("Hold");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.BookingItem", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.TimeBucket", "TimeBucket")
                        .WithMany("BookingItems")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Court", "Court")
                        .WithMany("BookingItems")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Court");

                    b.Navigation("TimeBucket");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.CheckoutOrder", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.AppUser", "User")
                        .WithMany("CheckoutOrders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.CheckoutOrderItem", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Booking", "Booking")
                        .WithMany("CheckoutOrderItems")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.CheckoutOrder", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.CourtBucket", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.TimeBucket", "TimeBucket")
                        .WithMany("CourtBuckets")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Court", "Court")
                        .WithMany("CourtBuckets")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("TimeBucket");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Hold", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.AppUser", "User")
                        .WithMany("Holds")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.HoldItem", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.TimeBucket", "TimeBucket")
                        .WithMany("HoldItems")
                        .HasForeignKey("BucketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Court", "Court")
                        .WithMany("HoldItems")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.Hold", "Hold")
                        .WithMany("HoldItems")
                        .HasForeignKey("HoldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Hold");

                    b.Navigation("TimeBucket");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.AppUser", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.PricingRule", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.AppUser", "CreatedByUser")
                        .WithMany("CreatedPricingRules")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.AppUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("RentalApp.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("RentalApp.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RentalApp.Domain.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("CheckoutOrders");

                    b.Navigation("CreatedPricingRules");

                    b.Navigation("Holds");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("Profile");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingItems");

                    b.Navigation("CheckoutOrderItems");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.CancellationPolicy", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.CheckoutOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Court", b =>
                {
                    b.Navigation("BookingItems");

                    b.Navigation("CourtBuckets");

                    b.Navigation("HoldItems");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Hold", b =>
                {
                    b.Navigation("HoldItems");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RentalApp.Domain.Entities.TimeBucket", b =>
                {
                    b.Navigation("BookingItems");

                    b.Navigation("CourtBuckets");

                    b.Navigation("HoldItems");
                });
#pragma warning restore 612, 618
        }
    }
}
